const LANGUAGE_DATA = {
    signupError:'Utilisateur déjà enregistré. Veuillez vous connecter avec vos identifiants!',
    userNotRegistered: "L'utilisateur n'est pas enregistré dans notre système, veuillez d'abord vous inscrire.",
    message:"écrivez votre message",
    exYear: 'ans',
    CHOOSE_PROFILE:{
        title:'Je souhaite',
        heading:'SmartTalent',
        button1:'Recruter',
        button2:'Postuler'
    },
    LOGIN:{
        heading:'SmartTalent',
        RoleRecuiter:'Recruteur',
        RoleCandidate:'Candidat',
        forgot:'Mot de passe oublié',
        button1:'Connexion',
        continuewith:'Ou continuer avec',
        createaccount:`Vous n’avez pas de compte?`,
        createaccount2:`  Créer un compte`,
    },
    FORGOT:{
        heading:'Mot de passe',
        heading2:'Oublié',
        recuitertitle:'Hi, Recruiter! Don’t worry, we just need your email-id to proceed with verification.',
        candidatetitle:'Ne vous inquiétez pas, nous avons juste besoin de votre e-mail afin de procéder à la vérification',
        enteremail:'Votre e-mail',
        button1:'Envoyer'
    },
    CREATE_ACCOUNT:{
        createyour:'Créez votre',
        account:'Compte',
        firstname:'Prénom',
        lastname:'Nom',
        email:'Email',
        phonenumber:'Numéro de téléphone',
        password:'Mot de passe',
        signupbutton:'Connexion',
        continuewith:'Ou continuer avec',
        alreadyaccount:'Vous avez déjà un compte?',
        login:' Connectez-vous'
    },
    OTP_PAGE:{
        heading:'Entrez le code de',
        heading2:'Vérification',
        button1:'Envoyer',
        resendtitle:'Vous n’avez pas reçu le code?',
        resendlink:' Renvoyer'
    },
    CREATE_PASSWORD:{
        heading:'Créez votre',
        password:'Mot de passe',
        title:'Créez votre nouveau mot de passe',
        enterpassword:'Mot de passe',
        confirmpassword:'Confirmer mot de passe',
        button:'Envoyer'
    },
    AVAILABILITY:{
        availability:'Disponible ?',
        button:'Suivant'
    },
    SEARCH:{
        search:'Recherche',
        position:'Type de contrat',
        sector:`Secteur d'activité`,
        location:'Secteur géographique',
        mode:'Mode de travail',
        onsite:'Présentiel',
        partialremote:'Télétravail partiel',
        remote:'100% Télétravail',
        button:'Suivant'
    },
    SKILL:{
        skill:'Compétences',
        title:'Indiquez les compétences dont vous maitrisez les bases ou des connaissances solides',
        slectskill:'Commencez à écrire',
        selectedskill:'Compétences sélectionnées',
        button:'Suivant'
    },
    EXPERIENCE:{
        experience:'Expériences',
        title:'Une expérience à nous faire parvenir ? Ne pas hésiter à décrire au maximum vos expériences !',
        add:'Ajouter +',
        jobtitle:'poste occupé',
        jobRecuitertitle:'poste recherché',
        location:'Lieu',
        category:'Société',
        startdate:'Date de début',
        enddate:'Date de fin',
        descrition:'Description',
        button:'Ajouter',
        button2:'Suivant',
        buttonEdit: 'Modifier'
    },
    DEGREE:{
        degree:'Diplômes',
        title:'Un diplôme à nous faire parvenir ? Ne pas hésiter à décrire au maximum vos diplômes!',
        add:'Ajouter +',
        degreename:'Nom du diplôme',
        schoolname:'École',
        startdate:'Date de début',
        enddate:'Date de fin',
        currently:'Je suis actuellement en étude',
        startwriting:'Compétences acquises',
        button:'Ajouter',
        button2:'Suivant'
    },
    VIDEO_INSTRUCTION:{
        video:'Vidéo',
        video1:'Votre offre en video',
        title:'Maintenant , présentez vous en une vidéo !Voici quelques idées pour réaliser le contenu de votre video :',
        point1:'Vidéo de moins de 1 minute',
        point2:'Indiquez votre nom et prénom',
        point3:'Indiquez vos expériences',
        point4:'Indiquez vos qualités et vos défauts',
        point5:'Indiquez vos valeurs',
        title2:'En cliquant sur “démarrer” vous aurez 5 secondes avant que l’enregistrement ne démarre.',
        button:'Enregistrer une vidéo de profil',
        buttonUpload:'Télécharger la vidéo de profil',
        point6:'La fonction de votre entreprise',
        point7:'Son activité'
    },
    VIDEO_PLAYBACK:{
        video:'Vidéo',
        title:'Bravo c’est dans la boîte ! voici un aperçu de ta vidéo. N’hésite pas à prendre le temps de la regarder dans les moindres détails',
        retry:'Recommencer',
        button:'Consulter les offres',
        recuiterbutton:'Voir les candidats',
        recordNew: 'Nouvel enregistrement',
    },
    ADD_COMPANY:{
        recuiter:'Je suis recruteur',
        candidate:'Je suis candidat',
        title:'Commencez par enregistrer votre entreprise',
        companyname:'Nom entreprise',
        description:`Présentation de l’entreprise`,
        selectsector:'Sélectionnez un secteur',
        sector:'secteur',
        logo:'Logo',
        import:'Importer',
        website:'Site web',
        companysize:'Taille de l’entreprise',
        button:'Suivant'
    },
    ADD_JOB:{
        createjob:'Créer une offre',
        jobtitle:'Titre du poste',
        selectexp:'Sélectionner expérience',
        location:'Ville(s)',
        language:'Langue(s) souhaitée(s)',
        certificate:'Diplôme(s) ou certification(s) souhaité(s)',
        salary:'Salaire',
        selectsalary:'Sélectionner salaire',
        emptype:'Type de contrat',
        selectemptype:'Sélectionner type de contrat',
        reqskill:'Compétences requises',
        secondarySkill:'Compétences recommandées',
        department: 'Département(s)',
        button:'Suivant',
        Select_Department:'Sélectionner Département'
    },
    noListMasgRecuiter: 'Nouveaux candidats bientôt disponibles',
    noListMasgCandidate: 'Nouvelles offres bientôt disponibles',
     masgCandidateNotMatch:'Le candidats doit matcher avec vous avant de pouvoir initier une discussion!',
    masgRecuiterNotMatch:'"Le recruteur doit matcher avec vous avant de pouvoir initier une discussion!',
    recuiterConversationNotStart: "Une fois que le recruteur aura initié la conversation, vous pourrez échanger avec lui.",
     "Search_Regions_or_city": "Rechercher un état ou une ville...",
    "Select_Regions_Cities": "Sélectionnez les États et les villes",
    Profile:'Profil',
    videoProfile: 'Profil vidéo',
    end_chat: 'Terminer la discussion',
};
const LANGUAGE_DATA2 = {
    message: 'Type a message',
    exYear: 'years',
    CHOOSE_PROFILE:{
        title:'I want :',
        heading:'SmartTalent',
        button1:'Recruter',
        button2:'Applicant',
    },
    LOGIN:{
        heading:'SmartTalent',
        RoleRecuiter:'Recuiter',
        RoleCandidate:'Candidat',
        forgot:'Forget Password',
        button1:'Login',
        continuewith:'Or Continue With',
        createaccount:`You don't have an account?`,
        createaccount2:`  Create an account`,
    },
    FORGOT:{
        heading:'Password',
        heading2:'Forgotten',
        recuitertitle:'Hi, Recruiter! Don’t worry, we just need your email-id to proceed with verification.',
        candidatetitle:'Hi, Applicant! Don’t worry, we just need your email-id to proceed with verification.',
        enteremail:'Enter E-mail',
        button1:'Send'
    },
    CREATE_ACCOUNT:{
        createyour:'Create Your',
        account:'Account',
        firstname:'First Name',
        lastname:'Last Name',
        email:'Email',
        phonenumber:'Phone Number',
        password:'Password',
        signupbutton:'Sign Up',
        continuewith:'or continue with',
        alreadyaccount:'Already have an account?',
        login:' Connectez-vous'
    },
    OTP_PAGE:{
        heading:'Enter The',
        heading2:'Verification Code',
        button1:'Send',
        resendtitle:`Didn't receive the code ?`,
        resendlink:' Resend'
    },
    CREATE_PASSWORD:{
        heading:'Create Your',
        password:'Password',
        title:'Create your new password',
        enterpassword:'Password',
        confirmpassword:'Confirm password',
        button:'Send'
    },
    AVAILABILITY:{
        availability:'Availability ?',
        button:'Next'
    },
    SEARCH:{
        search:'Search Information',
        position:'Position sought',
        sector:'Sector',
        location:'Location',
        mode:'Work Mode',
        onsite:'On Site',
        partialremote:'Partial/Remote Work',
        remote:'100% Remote',
        button:'Next'
    },
    SKILL:{
        skill:'Skills',
        title:'Indicate the skills of which you have mastered the basics or solid knowledge',
        slectskill:'Start writing',
        selectedskill:'Selected skills',
        button:'Next'
    },
    EXPERIENCE:{
        experience:'Expériences',
        title:'An experience to share with us? Don’t hesitate to describe your experiences as much as possible!',
        add:'Add +',
        jobtitle:'Job title',
        jobRecuitertitle:'Job title',
        location:'Location',
        category:'Company',
        startdate:'Date de début',
        enddate:'Date de fin',
        descrition:'Description',
        button:'Add',
        button2:'Next',
        buttonEdit: 'Edit',
    },
    DEGREE:{
        degree:'Degree',
        title:'A diploma to send us? Don’t hesitate to describe your qualifications as much as possible!',
        add:'Add +',
        degreename:'Name of degree',
        schoolname:'School',
        startdate:'Start date',
        enddate:'End date',
        currently:'I am currently studying',
        startwriting:'Skills acquired',
        button:'Add',
        button2:'Next'
    },
    VIDEO_INSTRUCTION:{
        video:'Video',
        title:'Now, present yourself in a video! Here are some ideas for creating the content of your video:',
        point1:'Video less than 1 minute',
        point2:'Indicate your first and last name',
        point3:'Indicate your experiences',
        point4:'Indicate your qualities and your faults',
        point5:'Indicate your values',
        title2:'By clicking on “start” you will have 5 seconds before the recording starts.',
        button:'Record Profile Video',
        buttonUpload:'Upload Profile Video'
    },
    VIDEO_PLAYBACK:{
        video:'Video',
        title:`Well done, it’s in the box! here is a preview of your video. Don't hesitate to take the time to look at it in every detail.`,
        retry:'Start again',
        button:'View offers',
        recuiterbutton:'View the candidates',
        recordNew: 'Record New', 
    },
    ADD_COMPANY:{
        recuiter:'I am a recruiter',
        candidate:'I am a candidate',
        title:'Start by registering your business',
        companyname:'Company name',
        description:'Description',
        selectsector:'Select an area',
        sector:'sector',
        logo:'Logo',
        import:'Import',
        website:'Website',
        companysize:'Company size',
        button:'Next'
    },
    ADD_JOB:{
        createjob:'Create an offer',
        jobtitle:'Job title',
        selectexp:'Select experience',
        location:'Location',
        language:'Desired language',
        certificate:'Diploma',
        salary:'Salary',
        selectsalary:'Select salary',
        emptype:'Type of contract',
        selectemptype:'Select contract type',
        reqskill:'Required skills',
        secondarySkill:'Good to have',
        button:'Next',
        department: 'Department',
        Select_Department:'Select Department'
        
    },
    noListMasgRecuiter: 'New Candidate List coming soon',
    noListMasgCandidate: 'New Recruiter List coming soon',
    masgCandidateNotMatch:'Candidate yet not except the match!',
    masgRecuiterNotMatch:'Recruiter yet not except the match!',
    recuiterConversationNotStart: "Once Recuiter will start conversation. Then you will able to chat with Recuiter.",
    "Search_Regions_or_city": "Search Regions or city...",
    "Select_Regions_Cities": "Select Regions & Cities",
    Profile:'Profile',
    videoProfile: 'Video Profile',
    end_chat: 'End Chat',
    signupError:'User Already registered. Please login with credentials!',
    userNotRegistered: 'User is not registered in our system, please registered first.',
};

export default LANGUAGE_DATA;
